#
# this is the default config file: it checks for basic sanity and cross-platform safety
#
dirs: [ "." ]
lints:
  - paths:
      - "**/*"
    rules:
      - no-msdos-reserved
      - no-whitespace
    rulesets:
      - linux
