#
# this is the config file for namelint itself
#
dirs: [ "." ]
ignore-dirs:
  - ".git"
  - ".jekyll-cache"
  - "target"
  - "_site"
lints:
  - paths:
      - "**/*"
    rules:
      - no-msdos-reserved
      - no-whitespace
      - posix-portable
