#
# _config.yml for www.namelint.dev
#

exclude: [ "CNAME" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
permalink: /blog/:year/:year-:month-:day-:slug:output_ext
production_url: https://www.namelint.dev
title: Namelint
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
