name: rule-validation

on:
  push:
    paths: ["rules", "docs/namelint-schema.yaml"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ajv
        run: |
          npm install -g ajv-cli
      - name: Run validation script
        run: |
          ./bin/validate.sh
